SELECT * FROM SPORTS;
SELECT * FROM PLAYERS;
SELECT * FROM COLLEGE;
SELECT * FROM TOURNAMENTS;
SELECT * FROM TOURNAMENTSPORTS;
SELECT * FROM TEAM;
SELECT * FROM SCOREBOARD;

CREATE TABLE REGISTEREDINDIVIDUALS(playerId int NOT NULL,tournamentId int NOT NULL,sportsId int NOT NULL);
CREATE TABLE REGISTEREDTEAMS(teamId int NOT NULL,tournamentId int NOT NULL,sportsId int NOT NULL);


ALTER TABLE REGISTEREDINDIVIDUALS ADD CONSTRAINT fk_tournament_individual FOREIGN KEY (tournamentID) REFERENCES TOURNAMENTS(tournamentID);
ALTER TABLE REGISTEREDINDIVIDUALS ADD CONSTRAINT fk_sports_individual FOREIGN KEY (sportsID) REFERENCES SPORTS(sportsID);
ALTER TABLE REGISTEREDINDIVIDUALS ADD CONSTRAINT fk_player_individual FOREIGN KEY (playerID) REFERENCES PLAYERS(playerID);

ALTER TABLE REGISTEREDTEAMS ADD CONSTRAINT fk_tournament_team FOREIGN KEY (tournamentID) REFERENCES TOURNAMENTS(tournamentID);
ALTER TABLE REGISTEREDTEAMS ADD CONSTRAINT fk_sports_team FOREIGN KEY (sportsID) REFERENCES SPORTS(sportsID);
ALTER TABLE REGISTEREDTEAMS ADD CONSTRAINT fk_team_team FOREIGN KEY (teamID) REFERENCES TEAM(teamID);
